name: Automated release (update version, commit, create release with changelog)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. 0.9.1)'
        required: true
      branch:
        description: 'Branch to update (default: master)'
        required: false
        default: 'master'
      create_release:
        description: 'Create GitHub release after committing (true/false)'
        required: false
        default: 'true'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update version in slackviewer/__init__.py
        run: |
          python3 scripts/update_version.py "${{ github.event.inputs.version }}" slackviewer/__init__.py

      - name: Commit version bump
        id: commit
        env:
          GIT_AUTHOR_NAME: "github-actions[bot]"
          GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
        run: |
          git config user.name "${GIT_AUTHOR_NAME}"
          git config user.email "${GIT_AUTHOR_EMAIL}"
          git add slackviewer/__init__.py
          git commit -m "Release ${{ github.event.inputs.version }} [skip ci]" || echo "No changes to commit"
          git push origin "${{ github.event.inputs.branch }}"

      - name: Fetch tags
        run: |
          git fetch --tags --prune

      - name: Generate changelog from commits since previous tag
        id: generate_changelog
        run: |
          # determine the most recent v* tag (previous release)
          PREV_TAG=$(git tag --list "v*" --sort=-creatordate | sed -n '1p' || true)
          echo "Previous tag: $PREV_TAG"
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found, generating changelog from repository root."
            python3 scripts/generate_changelog.py --output changelog.md
          else
            echo "Generating changelog from $PREV_TAG..HEAD"
            python3 scripts/generate_changelog.py --since "$PREV_TAG" --output changelog.md
          fi

          # Print changelog and set as step output for use in release body.
          echo "Changelog:"
          cat changelog.md || true

          # Write the changelog to GITHUB_OUTPUT for later steps to consume.
          # Use multi-line output format:
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat changelog.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        if: ${{ github.event.inputs.create_release == 'true' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          release_name: "${{ github.event.inputs.version }}"
          target_commitish: "${{ github.event.inputs.branch }}"
          body: ${{ steps.generate_changelog.outputs.changelog }}
